modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
[[mods]] #mandatory
modId="eoarmors" 
version="${file.jarVersion}" 
displayName="Ender Obsidian Armaments"
logoFile="icon.png" 
credits="EnhancedArmaments: TheXFactor117, JanneSoon. Thank you for 550 downloads on CurseForge!"
issueTrackerURL="https://github.com/Ragnaraven/EOArmaments/issues"
updateJSONURL="https://www.curseforge.com/minecraft/mc-mods/ender-obsidian-armaments/files"
authors="Ragnaraven" 
description='''
This mod adds Obsidian and Ender Obsidian as armor set with set special bonuses as end game mining tools

It also adds Emerald armor and tools as a tier above diamond.
.'''

[[dependencies.eoarmors]]
	    modId="forge"
	    mandatory=true
	    versionRange="[36,)"
	    ordering="NONE"
	    side="BOTH"

[[dependencies.eoarmors]]
	    modId="minecraft"
	    mandatory=true
	    versionRange="[1.16.5]"
	    ordering="NONE"
	    side="BOTH"